### ISSUE TITLE
media download stalls after a while

### ISSUE THREAD

**Issue by jclombar** [plantnet/gbif-dl#59]

**Comment by faroit** [comment]
Can you post your config?

**Comment by faroit** [comment]
I am about to implement #2 which might help

**Comment by faroit** [comment]
Maybe we also need #60?

**Comment by jclombar** [comment]
> Can you post your config?
* Build a data_generator as described in the README.md using species_id.json as "speciesKey" and providers.json as "datasetKey"
* launch a gbif_dl.io.download() on the data_generator with low nb_workers and tcp_connections (let's say 2 or 4)
* it will stall after a few thousand images

[providers.json.gz](https://github.com/plantnet/gbif-dl/files/6990942/providers.json.gz)
[species_id.json.gz](https://github.com/plantnet/gbif-dl/files/6990943/species_id.json.gz)

**Comment by faroit** [comment]
Okay, thanks... will check. I guess the first thing we would need to add is to provide a way to write out proper log files so that we can check for API or download errors. Hold on an let me try out some stuff

**Comment by faroit** [comment]
```python
import gbif_dl
data_generator = gbif_dl.dwca.generate_urls(
     "10.15468/dl.bx6xeq", 
     dwca_root_path="dwcas", 
     label="speciesKey"
)
gbif_dl.io.download(
    data_generator, 
    root="./imgs", 
    random_subsets={'train': 0.95, 'val': 0.05}, 
    nb_workers=100, 
    retries=1, 
    loglevel="INFO"
)
```
@jclombar do you have observed this also from a smaller query (that I can test again)?

**Comment by faroit** [comment]
@jclombar I observed a simular issue as you did when interrupting the internet connection (thus break the request session). Maybe that's the issue and I will try to find a way to resume the session now....

**Comment by faroit** [comment]
Thanks. Tracking it now

**Comment by faroit** [comment]
Hi @Christian-lyc I think we need to update the docs....

gbif_dl/stores/dl_async.py

Here is the download function now

**Comment by Christian-lyc** [comment]
Hi, thank you so much for your help, but there's another error occurs. I only download 1000 images, but it shows no space, which shouldn't be like that.

download(data_generator,root="/export/data/yliu/dataset",random_subsets={'train': 0.95, 'val': 0.05},nb_workers=20, retries=1,loglevel="INFO")

                                  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/yliu/.local/lib/python3.8/site-packages/gbif_dl/stores/dl_async.py", line 319, in download/s]
    return run_async(
  File "/export/home/yliu/.local/lib/python3.8/site-packages/gbif_dl/utils.py", line 63, in run_async
    return runners.run(func(*args, **kwargs))
  File "/export/home/yliu/.local/lib/python3.8/site-packages/gbif_dl/runners.py", line 104, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/export/home/yliu/.local/lib/python3.8/site-packages/gbif_dl/stores/dl_async.py", line 209, in _download_from_asyncgen
    async for batch in chnk:
  File "/export/home/yliu/.local/lib/python3.8/site-packages/aiostream/stream/transform.py", line 87, in chunks
    async for first in streamer:
  File "/export/home/yliu/.local/lib/python3.8/site-packages/aiostream/stream/create.py", line 34, in from_iterable
    for item in it:
  File "/export/home/yliu/.local/lib/python3.8/site-packages/gbif_dl/generators/dwca.py", line 47, in dwca_generator
    with DwCAReader(dwca_path) as dwca:
  File "/export/home/yliu/.local/lib/python3.8/site-packages/dwca/read.py", line 97, in __init__
    self._directory_to_clean, self._working_directory_path = self._extract()
  File "/export/home/yliu/.local/lib/python3.8/site-packages/dwca/read.py", line 448, in _extract
    extracted_dir = self._unzip_or_untar()
  File "/export/home/yliu/.local/lib/python3.8/site-packages/dwca/read.py", line 427, in _unzip_or_untar
    tmp_dir = mkdtemp()
  File "/usr/lib/python3.8/tempfile.py", line 497, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 28] No space left on device: '/tmp/tmpyk2gmouo'
